# Generated by Django 5.1.6 on 2025-03-07 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('categoria', models.CharField(max_length=255)),
                ('nome', models.CharField(max_length=255)),
                ('modelo', models.CharField(blank=True, max_length=255, null=True)),
                ('marca', models.CharField(default='Sem Marca', max_length=255)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('existente', models.IntegerField(default=0)),
                ('sku', models.CharField(max_length=20, unique=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_saida', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('endereco', models.CharField(default='Endereço Padrão', max_length=200)),
                ('cnpj', models.CharField(default='00.000.000/0000-00', max_length=20)),
                ('telefone', models.CharField(default='(00) 0000-0000', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ItemSaida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('preco_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetointegradors.produto')),
                ('saida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='projetointegradors.saida')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetointegradors.topic')),
            ],
        ),
    ]
