# Generated by Django 4.2.10 on 2024-09-28 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetointegradors', '0002_produto_saida_topic_cnpj_topic_endereco_and_more'),
        ('projetointegradors', '0012_produto_imagem'),
    ]

    operations = [
    ]
